# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-17 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_image',
            field=models.ImageField(default=b'default.png', upload_to=b'contacts_images'),
        ),
    ]
