# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20171127_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=15)),
                ('state', models.TextField(max_length=15)),
                ('zip', models.TextField(max_length=15)),
                ('country', models.TextField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
