# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-07 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20171225_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
