# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-15 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20171215_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_image',
            field=models.ImageField(default=b'default.png', upload_to=b'media/contacts_images'),
        ),
    ]
