# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20171128_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_selection',
            field=models.CharField(choices=[(b'HOME', b'Home Address'), (b'OFFICE', b'Office Address')], default=b'HOME', max_length=5),
        ),
    ]
