# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20171128_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_selection',
            field=models.CharField(choices=[(b'Home', b'Home Address'), (b'Office', b'Office Address')], default=b'Home', max_length=5),
        ),
    ]
